---
# Testing first NAE Ansible Module!!
# Note: This playbook is only to illustrate all module functionality. Running both add from change list and add from file 
#       will fail since only one PCA can run on NAE at a time.
- name: NAE TESTING
  hosts: all
  vars:
    nae_login: &nae_login
        host: 173.36.219.127
        port: 443  
        username: admin
        password: ins3965!ins3965! 
    validate_certs: False
  tasks:
  - name: Create a pre-change analysis from file
    nae_prechange:
      <<: *nae_login
      ag_name: lh-dmz1-pod1-aci-v32
      file: dump.json
      verify: True
      name: TestingfDumping
      state: present
...
